// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVIiK35PMFTvRgmmBkhLmdXahQFRfU9HM',
    appId: '1:1098968021274:web:e06b05387af784d7e454a3',
    messagingSenderId: '1098968021274',
    projectId: 'test-reg-14cbd',
    authDomain: 'test-reg-14cbd.firebaseapp.com',
    storageBucket: 'test-reg-14cbd.appspot.com',
    measurementId: 'G-G3DWWWTQK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotyS95_IRVkRXkkK5BrV8xYwX0KwJEJo',
    appId: '1:1098968021274:android:26d5cb646048cef6e454a3',
    messagingSenderId: '1098968021274',
    projectId: 'test-reg-14cbd',
    storageBucket: 'test-reg-14cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRPFN7O4HfNiIUOzqdTvrNG_TRWjXsQcM',
    appId: '1:1098968021274:ios:84bb5a4814d7acede454a3',
    messagingSenderId: '1098968021274',
    projectId: 'test-reg-14cbd',
    storageBucket: 'test-reg-14cbd.appspot.com',
    iosBundleId: 'com.example.authe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRPFN7O4HfNiIUOzqdTvrNG_TRWjXsQcM',
    appId: '1:1098968021274:ios:27351fc1083475abe454a3',
    messagingSenderId: '1098968021274',
    projectId: 'test-reg-14cbd',
    storageBucket: 'test-reg-14cbd.appspot.com',
    iosBundleId: 'com.example.authe.RunnerTests',
  );
}
